[package]
authors = ["Pascal Seitz <pascal.seitz@gmail.com>"]
autobenches = false
autobins = false
edition = "2018"
name = "veloci"
version = "0.1.1"

[[bench]]
harness = false
name = "bench_jmdict"
path = "benches/bench_jmdict.rs"

[[bench]]
name = "bench_collection"
path = "benches/bench_collection.rs"

[[bench]]
name = "bench_persistence"
path = "benches/bench_persistence.rs"

[dependencies]
byteorder = "1.3.2"
chrono = "0.4.9"
colored = "1.8.0"
cpuprofiler = "0.0.3"
crossbeam-channel = "0.3.9"
dot = "0.1.4"
dump = "0.1.1"
failure = "0.1.5"
fixedbitset = "0.1.9"
fnv = "1.0.6"
fst = "0.4.4"
itertools = "0.10.0"
lazy_static = "1.4.0"
log = "0.4.8"
lru-cache = "0.1.2"
lru_time_cache = "0.9.0"
measure_time = "0.6.0"
memmap = "0.7.0"
num = "0.2.0"
prettytable-rs = "0.8.0"
rayon = "1.2.0"
regex = "1.3.1"
ron = "0.5.1"
serde = "1.0.101"
serde_derive = "1.0.101"
serde_json = "1.0.40"
tempfile = "3.1.0"
toml = "0.5.3"
inohashmap = "0.2.1"
vint32 = { version = "0.2.0", features= ["common-encoding"]}

[dependencies.env_logger]
features = []
version = "0.7.1"

[dependencies.regex-automata]
features = ["transducer"]
version = "0.1.9"

[dependencies.buffered_index_writer]
path = "buffered_index_writer"

[dependencies.doc_store]
path = "doc_store"

[dependencies.half]
features = ["use-intrinsics", "serialize", "std"]
version = "1.3.0"

[dependencies.json_converter]
path = "json_converter"

[dependencies.levenshtein_automata]
features = ["fst_automaton"]
git = "https://github.com/PSeitz/levenshtein-automata"
branch = "ignore_case"

[dependencies.ordered-float]
features = ["serde"]
version = "1.0.2"

[dependencies.parking_lot]
features = ["nightly"]
version = "0.12.1"

# [dependencies.parser]
# path = "parser"

[dependencies.query_parser]
path = "query_parser"

# [dependencies.term_hashmap]
# git = "https://github.com/PSeitz/rust_string_hashmap"

[dev-dependencies]
more-asserts = "0.2.1"
pretty_assertions = "0.6.1"
rand = "0.7.2"

[dev-dependencies.color-backtrace]
version = "0.3.0"
default-features = false

[dev-dependencies.criterion]
features = []
version = "0.3.0"

[features]
create = []
unstable = []
default = ["create"]

[lib]
name = "veloci"
path = "src/lib.rs"

[workspace]
members = ["buffered_index_writer",
"doc_store",
"server",
"veloci_bins",
"json_converter",
"query_parser"]

[profile.release]
debug = true
lto = true
opt-level = 3
panic = "unwind"

[profile.bench]
debug = false
lto = true
opt-level = 3
