[package]
authors = ["Pascal Seitz <pascal.seitz@gmail.com>"]
name = "json_converter"
version = "0.1.0"
edition = "2021"
[[bench]]
harness = false
name = "bench"

[dependencies]
fnv = "1.0.7"
serde = "1.0.192"
serde_json = "1.0.108"


[dev-dependencies.criterion]
features = []
version = "0.5.1"
