[package]
authors = ["Pascal Seitz <pascal.seitz@gmail.com>"]
edition = "2018"
name = "doc_store"
version = "0.1.0"
[dependencies]
lz4_flex = { version = "0.10.0", default-features = false }
vint32 = { version = "0.3.0", features = ["common-encoding"] }
