name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup toolchain install stable
      - name: Install llvm
        run: rustup component add llvm-tools-preview --toolchain stable-x86_64-unknown-linux-gnu
      - uses: taiki-e/install-action@cargo-llvm-cov
      - name: Generate code coverage normal run  all-features
        run: cargo +nightly llvm-cov --all-features --workspace --lcov --output-path lcov1.info
      - name: Generate code coverage PersistenceType=Persistent LoadingType=Disk 
        run: PersistenceType=Persistent LoadingType=Disk cargo +nightly llvm-cov --workspace --lcov --output-path lcov2.info
      - name: Generate code coverage PersistenceType=Persistent LoadingType=InMemory 
        run: PersistenceType=Persistent LoadingType=InMemory cargo +nightly llvm-cov --workspace --lcov --output-path lcov2.info
      - name: Generate code coverage PersistenceType=Persistent LoadingType=Disk 
        run: PersistenceType=Persistent LoadingType=Disk cargo +nightly llvm-cov --workspace --lcov --output-path lcov3.info
      - name: Generate code coverage PersistenceType=Persistent LoadingType=Disk 
        run: PersistenceType=Transient FlushThreshold=20 cargo +nightly llvm-cov --workspace --lcov --output-path lcov4.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: lcov1.info,lcov2.info,lcov3.info,lcov4.info
          fail_ci_if_error: true


